create table staff(
staff_id int,
first_name varchar(50),
last_name varchar(50),
email varchar(100),
phone varchar(80),
active int,
store_id int,
manager_id int
)

create table store (
store_id int,
store_name varchar(50),
phone varchar(50),
email varchar(50),
street varchar(50),
city varchar(20),
state varchar(10),
zip_code int 
)

create table stock(
store_id	int,
product_id	int,
quantity	int
)


create table product(
product_id	int,
product_name	varchar(100),
brand_id	int,
category_id	int,
model_year	int,
list_price	decimal(10,3)

)



create table orders(
order_id int,
customer_id	int,
order_status int,
order_date date,
required_date date,
shipped_date date,
store_id int,
staff_id int
)


create table order_item(
order_id	int,
item_id	int,
product_id	int,
quantity	int,
list_price	decimal(10,4),
discount	decimal(10,4)
)



create table customer(
customer_id	int,
first_name varchar(20),
last_name varchar(20),
email varchar(60),
street varchar(70),
city varchar(30),
state varchar(10),
zip_code varchar(15)
)


create table categories(
category_id	int,
category_name varchar(50)
)


create table brand(
brand_id	int,
brand_name	varchar(20)
)




1. Top-selling product 
-- Find the top 10 products based on total quantity sold across 
-- all stores  

SELECT p.product_id,
	   p.product_name,
	   sum(ot.quantity) AS total_quantity 
FROM 
  	product AS p
JOIN 
	order_item AS ot
ON p.product_id = ot.product_id
GROUP BY 1,2 
ORDER BY total_quantity DESC
LIMIT 10



2 Revenue by category 
-- calculate the total revenue generated by each product category
-- after considering discounts.

SELECT c.category_id,
	   c.category_name,
	   Round(SUM(
	   (oi.quantity*oi.list_price*(1-oi.discount)
	   )),2) AS  Revenue_generated
FROM
	product AS p
JOIN categories AS c
	ON p.category_id = c.category_id
JOIN order_item as oi 
	ON  p.product_id=oi.product_id
group by 1,2
order by Revenue_generated desc 

3 store-wise sales performances 
-- Find the total sales revenue generated by each store and 
-- rank the stores from highest to lowest revenue 

SELECT st.store_name, 
	Round(SUM(
	   (oi.quantity*oi.list_price*(1-oi.discount)
	   )),2) AS  Revenue_generated,
RANK() OVER(
		ORDER BY SUM(oi.quantity*oi.list_price*(1-oi.discount))
		desc) as rank_store
FROM store AS st
JOIN 
	orders AS o
ON st.store_id=o.store_id
JOIN
	order_item AS oi
ON o.order_id=oi.order_id 
GROUP BY store_name 

4 Customer order analysis 
-- Identify customers who have placed more than 5 orders and 
-- show their total spending 

select c.first_name,c.last_name,
	   count(oi.order_id) AS Total_orders,
	   Round(SUM((oi.quantity*oi.list_price*(1-oi.discount)))
	   ) AS Total_spending
FROM customer AS c
JOIN 
	orders AS o
ON c.customer_id = o.customer_id
JOIN
	order_item AS oi
ON o.order_id = oi.order_id 
GROUP BY  1,2
HAVING (COUNT(oi.order_id)>=5)
ORDER BY total_orders DESC	


5 Staff performance 
-- Determine which staff member has the largest number of orders and 
-- Calculate the revenue generated by the staff members 

select s.first_name,s.last_name,
	   count(oi.order_id) as Total_orders,
	   Round(SUM((oi.quantity*oi.list_price*(1-oi.discount)))
	   ) AS revenue_generated 
FROM staff AS s
JOIN 
	orders AS o
ON s.staff_id = o.staff_id 
JOIN order_item AS oi
on o.order_id = oi.order_id 
GROUP BY 1,2
ORDER BY revenue_generated desc 


Advance level
6. Best-selling product in each category 
-- for every category, find the product with the highest sales 
-- quantity 

WITH product_sales AS (
SELECT  c.category_id,c.category_name,
		p.product_name,
		SUM(oi.quantity) AS Total_quantity, 
DENSE_RANK() OVER(PARTITION BY c.category_name 
		ORDER BY  SUM(oi.quantity) DESC) AS RANK
FROM order_item AS oi
JOIN product AS p
ON  oi.product_id = p.product_id 
JOIN categories AS c
ON  p.category_id=c.category_id 
GROUP BY 1,2,3
)
SELECT category_id,category_name,
		product_name,total_quantity
FROM product_sales 
WHERE RANK =1

7. Monthly revenue growth 
-- Calculate the month-over-month revenue growth percentage
-- for each store 

with monthly_sale as(
select  s.store_id,s.store_name,
		Date_trunc('month',o.order_date) as month,
		Round(SUM((oi.quantity*oi.list_price*(1-oi.discount)))
	   ) AS revenue
FROM store AS s 
JOIN orders AS o
ON s.store_id=o.store_id
join order_item AS oi
on o.order_id = oi.order_id
group by 1,2,3
)
select store_id,store_name,
	   month, revenue,
	   lag(revenue) over(partition by store_id order by month) 
	   as previous_month_revenue,
round(
	(revenue-lag(revenue)over(partition	by store_id order by month desc))
	/
	lag(revenue) over(partition by store_id order by month)*100,2)
	as growth_percentage
from monthly_sale
order by store_id desc


8 Inventory Risk Analysis 
-- find products whose current stock quantity is below the average 
-- stock quantity of products within the name category 
SELECT  p.product_id,p.product_name,
		c.category_name,
		SUM(s.quantity) AS current_stock
FROM product AS p
JOIN categories AS c
ON p.category_id=c.category_id
JOIN stock AS s
ON s.product_id = p.product_id 
GROUP BY 1,2,3,p.category_id
HAVING SUM(s.quantity)<
(
	SELECT AVG(product_stock)
	FROM
	(
	SELECT p2.product_id,
		   AVG(s2.quantity) AS product_stock
 	FROM product AS p2
	JOIN stock AS s2
	ON P2.product_id = s2.product_id
	WHERE p2.category_id=p.category_id
	GROUP BY  1
	)avg_stock
	)
	ORDER BY current_stock
-- select  p.product_id,p.product_name,
-- 		c.category_name,
-- 		sum(s.quantity) as total_quantity
-- from product AS p
-- join stock AS s
-- on p.product_id = s.product_id
-- join categories as c
-- on p.category_id= c.category_id
-- group by 1,2,3
-- having sum(s.quantity)<
-- (
-- 	select(avg(productstocks))
-- 	from(
-- 		select avg(quantity) as productstocks
-- 		from stock 
-- 	))


9. Customer lifeline value(CLV)
-- Calculate the lifetime value of each customer and
-- Identify the top 10 customers by total revenue

SELECT  c.customer_id,c.first_name,
		count(DISTINCT o.order_id) AS total_orders,
		Round(SUM(
	   (oi.quantity*oi.list_price*(1-oi.discount)
	   )),2) AS  customer_lifetime_value
FROM customer AS c
JOIN orders AS o
ON c.customer_id=o.customer_id
JOIN order_item AS oi
ON o.order_id=oi.order_id
GROUP BY 1,2
ORDER BY customer_lifetime_value DESC 
LIMIT 10

10. Store and Category Revenue Contribution
-- For each store, calculate what percentage of total store revenue 
-- comes from each category

WITH category_revenue AS (
SELECT st.store_id,st.store_name,
		c.category_name,
		Round(SUM(
	   (oi.quantity*oi.list_price*(1-oi.discount)
	   )),2) AS  revenue 
FROM store AS st
JOIN orders AS o 
ON st.store_id=o.store_id
JOIN order_item AS oi
ON o.order_id=oi.order_id
JOIN product AS p
ON p.product_id=oi.product_id 
JOIN categories AS c
ON c.category_id=p.category_id
GROUP BY 1,2,3
)
SELECT  store_id,
		store_name,category_name,
		revenue,
	round(revenue*100/SUM(revenue)OVER(PARTITION BY  store_id)),2
	AS revenue_percentage 
FROM category_revenue 
ORDER BY  store_id,revenue_percentage  th
-- created tables 
select * from staff
select * from store 
select * from stock 
select * from product
select * from orders 
select * from order_item
select * from customer 
select * from categories 
select * from brand 


























